from services.books import (
    BOOK_GENRES,
    BOOK_PRICE_FILTERS,
    build_book_filters,
    count_books,
    format_price_cents,
    get_book_by_id,
    init_books_db,
    list_book_genres,
    list_book_languages,
    list_books,
    normalize_book_genre,
    parse_price_text,
    search_books,
)
from services.db import close_db, ensure_table_columns, get_books_db, get_db
from services.orders import (
    create_order_for_user,
    delete_order,
    get_order_by_id,
    list_all_orders,
    list_user_orders,
    update_order_status,
)
from services.users import (
    ALLOWED_IMAGE_EXTENSIONS,
    AppUser,
    allowed_image_file,
    as_app_user,
    get_admin_settings,
    get_preferred_form,
    get_profile_image_url,
    get_user_by_email,
    get_user_by_id,
    init_users_db,
    is_valid_image_bytes,
    normalize_email,
)
from services.wishlist import (
    add_wishlist_book,
    has_wishlist_book,
    list_wishlist_book_ids,
    list_wishlist_books,
    remove_wishlist_book,
)


__all__ = [
    "ALLOWED_IMAGE_EXTENSIONS",
    "AppUser",
    "BOOK_GENRES",
    "BOOK_PRICE_FILTERS",
    "add_wishlist_book",
    "allowed_image_file",
    "as_app_user",
    "build_book_filters",
    "close_db",
    "count_books",
    "create_order_for_user",
    "delete_order",
    "ensure_table_columns",
    "format_price_cents",
    "get_admin_settings",
    "get_book_by_id",
    "get_books_db",
    "get_db",
    "get_order_by_id",
    "get_preferred_form",
    "get_profile_image_url",
    "get_user_by_email",
    "get_user_by_id",
    "has_wishlist_book",
    "init_books_db",
    "init_db",
    "init_users_db",
    "is_valid_image_bytes",
    "list_all_orders",
    "list_book_genres",
    "list_book_languages",
    "list_books",
    "list_user_orders",
    "list_wishlist_book_ids",
    "list_wishlist_books",
    "normalize_book_genre",
    "normalize_email",
    "parse_price_text",
    "remove_wishlist_book",
    "search_books",
    "update_order_status",
]


def init_db() -> None:
    init_users_db()
